### PR TITLE
SC-11280 copy changes done in sonarcloud-core

### PR DESCRIPTION
**Pull request by dbmeneses**

### CODE REVIEW

**Review by cody-simms-sonarsource — APPROVED** [review]

**Comment by dbmeneses** [comment]
@sebastienvermeille looks like it's not able to get the promote credentials from the vault. Could you please help me figure this out?

**Comment by pierre-guillot-gh** [comment]
hey @dbmeneses does this PR still make sense? Should the Analysis Experience take over? (cc @henryju )

**Comment by henryju** [comment]
I think sonar-classloader goes together with the sonar-plugin-api so we should be responsible for this repo.

**Comment by dbmeneses** [comment]
> hey @dbmeneses does this PR still make sense? Should the Analysis Experience take over? (cc @henryju )

Yes, changes should be moved to this repo, and then we can remove the duplication from sonarcloud-core and sonarqube.
This is used by the scanner-engine to load plugins, so it is part of the analysis experience.

**Pull request merged**
